### PR TITLE
Remote services 1.4.x (WIP)

### PR DESCRIPTION
**Pull request by davisc**
This PR does the following:

1. Pulls forward changes from Upstream Geonode Master which includes migrations files
2. Adds a handler for esri rest mapserver services
3. Updates the templates to reflect the workflow
4. Fixes bug where processing would halt if the service only had 1 layer.
5. Adds ArcREST-Package==3.5.9
6. Updates the ESRI service parsing to extract the service name and title rather than the mapName which in most cases was always set to the value 'Layers'. This allows for better parity between what's registered in Exchange and what metadata is published via the ESRI html pages.
7. Adds attribute field extraction and persistence for ESRI services.
8. Reenables the layer details page for remote services.
9. Adds the references/supplemental links to the layer index and Links table
10. Adds source_host to the layers index
11. Add bbox fields to the document metadata edit form

### CODE REVIEW

**Comment by amirahav** [comment]
Noticed these when trying the PR:

- Clicking on `Register a new Service` fails to load/render with:
```
ERROR:django.request:Internal Server Error: /services/register/
Traceback (most recent call last):
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/geonode/services/views.py", line 90, in register_service
    request, service_register_template, {"form": form})
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 959, in render
    output = self.filter_expression.resolve(context)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django/template/base.py", line 675, in resolve
    new_obj = func(obj, *arg_vals)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py", line 30, in as_bootstrap
    form = _preprocess_fields(form)
  File "/opt/boundless/exchange/.venv/lib/python2.7/site-packages/django_forms_bootstrap/templatetags/bootstrap_tags.py", line 17, in _preprocess_fields
    for field in form.fields:
AttributeError: 'str' object has no attribute 'fields'
```

- publishing a "regular" layer succeeds, however viewing the layer in geonode fails (`detail_url` is  `/layers/None`). Viewing also fails in maploom when adding the layer via search/map (layer name is `None`).

- Running `makemigrations` creates the following migrations:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0029_layer_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='abstract_en',
            field=models.TextField(help_text='brief narrative summary of the content of the resource(s)', null=True, verbose_name='abstract', blank=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_quality_statement_en',
            field=models.TextField(help_text="general explanation of the data producer's knowledge about the lineage of a dataset", null=True, verbose_name='data quality statement', blank=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='default_style',
            field=models.ForeignKey(related_name='layer_default_style', blank=True, to='layers.Style', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='purpose_en',
            field=models.TextField(help_text='summary of the intentions with which the resource(s) was developed', null=True, verbose_name='purpose', blank=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='supplemental_information_en',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', null=True, verbose_name='supplemental information'),
        ),
    ]
```

and
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '26_to_27'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='group',
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='tkeywords',
            field=models.ManyToManyField(help_text='formalised word(s) or phrase(s) from a fixed thesaurus used to describe the subject (space or comma-separated', to='base.ThesaurusKeyword', null=True, blank=True),
        ),
    ]
```

If an older version of exchange/geonode is already installed, running `migrate` will throw this warning:
```
The following content types are stale and need to be deleted:

    services | servicelayer
    services | webserviceregistrationjob
    services | webserviceharvestlayersjob

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
```
We should create a migration to delete those tables, instead of requiring a user to accept those changes.

**Comment by davisc** [comment]
@amirahav thanks for the feedback... Regarding `Clicking on Register a new Service fails to load/render `, in order to test end-to-end, I need to make an Exchange PR so that the updated templates can be used.

**Comment by davisc** [comment]
@amirahav running `makemigrations` should now result in `no changes detected`

**Comment by amirahav** [comment]
Thanks @davisc, and sounds good.

**Pull request merged**
